# Generated by Django 4.1.5 on 2023-04-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
